# Rebuild website content whenever the source changes
name: Update GitHub Pages

on:
    push:
        branches:
            - main

    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    main:
        runs-on: ubuntu-latest

        steps:
            - name: 📲 Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: 🧩 Install dependencies
              run: |
                  npm install -g pnpm
                  export PNPM_HOME="$HOME/.local/share/pnpm"
                  export PATH="$PNPM_HOME:$PATH"
                  pnpm env use --global latest

            - name: 🚧 Build using SvelteKit
              run: |
                  pnpm install
                  pnpm run build

            - name: 🚀 Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build
                  branch: deploy
