# Rebuild website content whenever the source changes
name: Update GitHub Pages

on:
  push:
    branches:
      - main

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # Check out the template repository
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Run the generator script
        run: sh ./scripts/deploy.sh "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
